# Generated by Django 2.1.5 on 2019-02-06 11:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings_agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(max_length=200)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('main_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('secondary_photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('secondary_photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('secondary_photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('secondary_photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('secondary_photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('secondary_photo6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings_agents.Agent')),
            ],
        ),
    ]
